const en = {
  nav: {
    how: "How it works",
    features: "Features",
    story: "Story",
    award: "Recognition",
    faq: "FAQ",
    cta: "Launch Smartboard",
    menu: "Menu",
  },
  hero: {
    badge: "2nd place worldwide · Gemma 4 Good Hackathon by Google",
    h1a: "Teach out loud.",
    h1b: "The board listens.",
    sub: "TRIDO is the AI smartboard you run entirely with your voice. Say what you want to teach — it draws the mind map, writes the notes and opens the timer while your eyes stay on your students.",
    cta1: "Launch Smartboard",
    cta2: "Watch it work",
    downloadExe: "Download Desktop App (.exe)",
    downloadExeSub: "Standalone Windows Desktop App · No Terminal Needed",
    meta: ["Voice-first", "Cloud + offline mode", "English & Bahasa Indonesia"],
    try: "Try it — pick a lesson",
  },
  demo: {
    classroom: "Digital Classroom",
    cloud: "Cloud Mode",
    assistant: "Assistant",
    share: "Share",
    save: "Save",
    teacher: "Teacher",
    classLead: "Class instructor",
    ready: "All systems ready",
    readySub: "Voice ready · tap a lesson",
    listening: "Listening",
    listeningSub: "Speak naturally",
    thinking: "AI agent responding",
    thinkingSub: "Planning the board",
    done: "Done on the board",
    doneSub: "Edit, present or export",
    tabs: ["Mind map", "Document", "Classroom tools"],
    say: [
      "Make a mind map about poetry",
      "Summarize the basic accounting equation",
      "Start a five minute timer and open the scoreboard",
    ],
    mm: {
      title: "Poetry — concept map",
      center: "Poetry",
      elements: "Elements",
      inner: "Inner",
      innerSub: "Theme, mood, message",
      outer: "Outer",
      outerSub: "Diction, imagery, rhyme",
      types: "Types",
      old: "Old poetry",
      oldSub: "Pantun, Syair, Gurindam",
      modern: "Modern",
      modernSub: "Ballad, Ode, Epigram",
    },
    doc: {
      label: "Study document",
      title: "Basic Accounting Equation",
      intro:
        "The basic accounting equation is the foundation of double-entry bookkeeping for any business.",
      h1: "1. Core formula",
      formula: "Assets = Liabilities + Equity",
      h2: "2. Key components",
      items: [
        ["Assets", "what the business owns"],
        ["Liabilities", "what it owes"],
        ["Equity", "the owners' claim"],
      ],
    },
    tools: {
      timer: "Timer",
      score: "Scoreboard",
      teams: ["Team A", "Team B", "Team C"],
    },
  },
  marquee: [
    "Make a mind map about the water cycle",
    "Start a five minute timer",
    "Summarize chapter three",
    "Open the random wheel",
    "Quiz the class on fractions",
    "Show the periodic table",
    "Take attendance",
    "Graph y equals x squared",
    "Convert 5 kilometres to miles",
    "Add a new page",
  ],
  how: {
    pill: "01",
    kicker: "How it works",
    title: "From a sentence to a lesson.",
    steps: [
      {
        t: "Speak",
        d: "Press the mic, or just talk. TRIDO listens in English or Bahasa Indonesia.",
      },
      {
        t: "Understand",
        d: "An AI agent works out what you mean — a diagram, a summary, a tool — and plans the board.",
      },
      {
        t: "Appear",
        d: "Content lands on the canvas, ready to move, edit, present, share or export.",
      },
    ],
  },
  features: {
    pill: "02",
    kicker: "What's on the board",
    title: "Everything a lesson needs. Nothing to tap through.",
    mm: { t: "Concept maps on command", d: "Name a topic. TRIDO lays out branches, colours and links — and you can keep editing by hand." },
    doc: { t: "Notes that write themselves", d: "Structured study documents with headings and formulas, ready to present or export." },
    widgets: {
      t: "11 classroom widgets",
      d: "Ask for a tool and it opens on the board.",
      list: [
        "Calculator",
        "Timer",
        "Notes",
        "AI Quiz",
        "Converter",
        "Periodic",
        "Attendance",
        "To-Do",
        "Random Wheel",
        "Scoreboard",
        "Math Graph",
      ],
    },
    cloud: { t: "Cloud power. Offline backup.", d: "Full AI in cloud mode. When the connection drops, keep teaching with limited voice recording or text." },
    share: { t: "Present, share, export", d: "Multiple pages, undo and redo, zoom and one-tap sharing." },
    pen: { t: "Still a whiteboard", d: "Pen, shapes, text and images by touch. Voice comes first — never the only way." },
    cloudOn: "Cloud",
    cloudOff: "Offline",
  },
  story: {
    pill: "03",
    kicker: "Why we built it",
    title: "It started with one teacher.",
    p1: "Pak Dadan M. Ramdhan — “Pak Damar” — teaches Bahasa Indonesia at SMPN 20 Bandung. He lives with a disability and has never stopped teaching.",
    p2: "He became the starting point of all our research. What if the board adapted to the teacher, instead of the other way around?",
    name: "PAK DAMAR",
    role: "Bahasa Indonesia teacher",
    sticker: "Voice-first is access.",
    tagline: "TRIDO: Together building inclusive education",
  },
  award: {
    pill: "04",
    kicker: "Recognition",
    title: "2nd place in the world.",
    sub: "Gemma 4 Good Hackathon by Google — a challenge to build with Gemma 4 for real-world impact.",
    timeline: [
      { t: "Found the challenge", d: "Ardellio follows AI competitions and hackathons closely. He spotted the Gemma 4 Good Hackathon on Kaggle." },
      { t: "Built it together", d: "Azhar was invited to join. The research began with Pak Damar and his classroom." },
      { t: "Placed 2nd worldwide", d: "TRIDO: AI-based voice smartboard. Presented in 2026." },
    ],
    stats: [
      { n: "2", s: "nd", l: "place worldwide" },
      { n: "11", s: "", l: "classroom widgets" },
      { n: "2", s: "", l: "languages" },
      { n: "100", s: "%", l: "voice-controlled" },
    ],
    by: "Presented by",
  },
  faq: {
    pill: "05",
    kicker: "FAQ",
    title: "Good questions.",
    items: [
      { q: "Do I need special hardware?", a: "TRIDO runs in the browser. Any interactive display, laptop or tablet with a microphone will do." },
      { q: "Which languages does it understand?", a: "English and Bahasa Indonesia — and the whole interface switches with one tap." },
      { q: "What if the internet drops?", a: "Offline mode keeps the basics going: record your voice or type. Cloud mode brings the full AI back when you reconnect." },
      { q: "Is it voice only?", a: "No. Pen, shapes, text and images work by touch too. Voice is first, never the only way." },
      { q: "How can my school try it?", a: "Request a demo below and we'll get in touch." },
    ],
  },
  cta: {
    pill: "06",
    title: "Bring TRIDO to your classroom.",
    sub: "Leave your email and we'll arrange a live demo — in English or Bahasa Indonesia.",
    placeholder: "you@school.id",
    button: "Request a demo",
    thanks: "Thank you — let's talk!",
    thanksSub: "We'll be in touch very soon.",
    invalid: "Please enter a valid email.",
  },
  footer: {
    rights: "© 2026 TRIDO. All rights reserved.",
    top: "Back to top",
  },
};

export type Dict = typeof en;

const id: Dict = {
  nav: {
    how: "Cara kerja",
    features: "Fitur",
    story: "Cerita",
    award: "Penghargaan",
    faq: "FAQ",
    cta: "Buka Smartboard",
    menu: "Menu",
  },
  hero: {
    badge: "Juara 2 Dunia · Gemma 4 Good Hackathon by Google",
    h1a: "Mengajar lewat suara.",
    h1b: "Papan yang mendengar.",
    sub: "TRIDO adalah smartboard AI yang dikendalikan sepenuhnya dengan suara. Ucapkan yang ingin Anda ajarkan — papan menggambar peta konsep, menulis catatan, dan membuka timer, sementara mata Anda tetap tertuju pada murid.",
    cta1: "Buka Smartboard",
    cta2: "Lihat cara kerjanya",
    downloadExe: "Unduh App Desktop (.exe)",
    downloadExeSub: "Aplikasi Windows Standalone · Siap Pakai Tanpa Terminal",
    meta: ["Suara lebih dulu", "Mode Cloud + Offline", "Bahasa Indonesia & English"],
    try: "Coba — pilih satu pelajaran",
  },
  demo: {
    classroom: "Digital Classroom",
    cloud: "Mode Cloud",
    assistant: "Asisten",
    share: "Bagikan",
    save: "Simpan",
    teacher: "Guru",
    classLead: "Pengajar Kelas",
    ready: "Semua sistem siap",
    readySub: "Suara siap · pilih pelajaran",
    listening: "Mendengarkan",
    listeningSub: "Bicara saja secara natural",
    thinking: "Agen AI merespons",
    thinkingSub: "Menyusun papan",
    done: "Selesai di papan",
    doneSub: "Edit, presentasikan, atau ekspor",
    tabs: ["Peta konsep", "Dokumen", "Alat kelas"],
    say: [
      "Buatkan peta konsep tentang puisi",
      "Rangkum persamaan dasar akuntansi",
      "Mulai timer lima menit dan buka papan skor",
    ],
    mm: {
      title: "Peta Konsep Puisi",
      center: "Puisi",
      elements: "Unsur Puisi",
      inner: "Unsur Batin",
      innerSub: "Tema, rasa, nada, amanat",
      outer: "Unsur Fisik",
      outerSub: "Diksi, imaji, rima",
      types: "Jenis Puisi",
      old: "Puisi Lama",
      oldSub: "Pantun, Syair, Gurindam",
      modern: "Puisi Baru",
      modernSub: "Balada, Ode, Epigram",
    },
    doc: {
      label: "Dokumen belajar",
      title: "Persamaan Dasar Akuntansi",
      intro:
        "Persamaan dasar akuntansi adalah fondasi utama pencatatan keuangan perusahaan yang menggunakan sistem double-entry.",
      h1: "1. Rumus Utama",
      formula: "Aset = Liabilitas + Ekuitas",
      h2: "2. Komponen Utama",
      items: [
        ["Aset", "yang dimiliki usaha"],
        ["Liabilitas", "kewajiban usaha"],
        ["Ekuitas", "hak pemilik"],
      ],
    },
    tools: {
      timer: "Timer",
      score: "Papan Skor",
      teams: ["Tim A", "Tim B", "Tim C"],
    },
  },
  marquee: [
    "Buatkan peta konsep siklus air",
    "Mulai timer lima menit",
    "Rangkum bab tiga",
    "Buka roda acak",
    "Kuis kelas tentang pecahan",
    "Tampilkan tabel periodik",
    "Catat presensi hari ini",
    "Gambar grafik y sama dengan x kuadrat",
    "Konversi 5 kilometer ke meter",
    "Tambah halaman baru",
  ],
  how: {
    pill: "01",
    kicker: "Cara kerja",
    title: "Dari satu kalimat jadi satu pelajaran.",
    steps: [
      {
        t: "Ucapkan",
        d: "Tekan mikrofon, atau langsung bicara. TRIDO mendengar dalam Bahasa Indonesia atau English.",
      },
      {
        t: "Pahami",
        d: "Agen AI menangkap maksud Anda — diagram, rangkuman, atau alat — lalu menyusun papan.",
      },
      {
        t: "Muncul",
        d: "Konten hadir di kanvas, siap digeser, diedit, dipresentasikan, dibagikan, atau diekspor.",
      },
    ],
  },
  features: {
    pill: "02",
    kicker: "Isi papan",
    title: "Semua kebutuhan pelajaran. Tanpa menu berlapis.",
    mm: { t: "Peta konsep sesuai perintah", d: "Sebut topiknya. TRIDO menata cabang, warna, dan hubungan — tetap bisa Anda edit manual." },
    doc: { t: "Catatan yang menulis dirinya sendiri", d: "Dokumen belajar terstruktur dengan judul dan rumus, siap dipresentasikan atau diekspor." },
    widgets: {
      t: "11 widget kelas",
      d: "Minta satu alat, dan alat itu terbuka di papan.",
      list: [
        "Kalkulator",
        "Timer",
        "Catatan",
        "Kuis AI",
        "Konversi",
        "Periodik",
        "Presensi",
        "To-Do",
        "Roda Acak",
        "Papan Skor",
        "Grafik MTK",
      ],
    },
    cloud: { t: "Tenaga cloud. Cadangan offline.", d: "AI penuh di mode cloud. Saat koneksi putus, tetap mengajar dengan rekam suara terbatas atau teks." },
    share: { t: "Presentasi, bagikan, ekspor", d: "Banyak halaman, undo dan redo, zoom, dan berbagi sekali sentuh." },
    pen: { t: "Tetap papan tulis", d: "Pena, bentuk, teks, dan gambar lewat sentuhan. Suara yang utama — bukan satu-satunya cara." },
    cloudOn: "Cloud",
    cloudOff: "Offline",
  },
  story: {
    pill: "03",
    kicker: "Mengapa kami membuatnya",
    title: "Semua berawal dari satu guru.",
    p1: "Pak Dadan M. Ramdhan — “Pak Damar” — mengajar Bahasa Indonesia di SMPN 20 Bandung. Beliau penyandang disabilitas dan tidak pernah berhenti mengajar.",
    p2: "Beliau menjadi titik awal seluruh riset kami. Bagaimana jika papan yang menyesuaikan diri dengan guru, bukan sebaliknya?",
    name: "PAK DAMAR",
    role: "Guru Bahasa Indonesia",
    sticker: "Suara itu akses.",
    tagline: "TRIDO: Bersama Wujudkan Pendidikan Inklusif",
  },
  award: {
    pill: "04",
    kicker: "Penghargaan",
    title: "Juara 2 Dunia.",
    sub: "Gemma 4 Good Hackathon by Google — tantangan membangun solusi dengan Gemma 4 untuk dampak nyata.",
    timeline: [
      { t: "Menemukan tantangan", d: "Ardellio rutin memantau kompetisi AI & hackathon. Ia menemukan Gemma 4 Good Hackathon di Kaggle." },
      { t: "Membangun bersama", d: "Azhar diajak bergabung. Riset dimulai dari Pak Damar dan kelasnya." },
      { t: "Juara 2 dunia", d: "TRIDO: AI Berbasis Suara Smartboard. Dipresentasikan pada 2026." },
    ],
    stats: [
      { n: "2", s: "", l: "juara dunia" },
      { n: "11", s: "", l: "widget kelas" },
      { n: "2", s: "", l: "bahasa" },
      { n: "100", s: "%", l: "dikendalikan suara" },
    ],
    by: "Dipresentasikan oleh",
  },
  faq: {
    pill: "05",
    kicker: "FAQ",
    title: "Pertanyaan yang sering muncul.",
    items: [
      { q: "Apakah perlu perangkat khusus?", a: "TRIDO berjalan di browser. Layar interaktif, laptop, atau tablet dengan mikrofon sudah cukup." },
      { q: "Bahasa apa yang dipahami?", a: "Bahasa Indonesia dan English — seluruh antarmuka berganti hanya dengan satu sentuhan." },
      { q: "Bagaimana jika internet putus?", a: "Mode offline menjaga dasar-dasarnya: rekam suara atau ketik. Mode cloud mengembalikan AI penuh saat tersambung kembali." },
      { q: "Apakah hanya lewat suara?", a: "Tidak. Pena, bentuk, teks, dan gambar juga bisa lewat sentuhan. Suara yang utama, bukan satu-satunya." },
      { q: "Bagaimana sekolah saya bisa mencoba?", a: "Minta demo di bawah ini dan kami akan menghubungi Anda." },
    ],
  },
  cta: {
    pill: "06",
    title: "Bawa TRIDO ke kelas Anda.",
    sub: "Tinggalkan email Anda dan kami akan mengatur demo langsung — dalam Bahasa Indonesia atau English.",
    placeholder: "anda@sekolah.id",
    button: "Minta demo",
    thanks: "Terima kasih — mari berdiskusi!",
    thanksSub: "Kami akan segera menghubungi Anda.",
    invalid: "Masukkan email yang valid.",
  },
  footer: {
    rights: "© 2026 TRIDO. Hak cipta dilindungi.",
    top: "Kembali ke atas",
  },
};

export const dict = { en, id };
export type Lang = keyof typeof dict;
